import fileinput
import math
import collections
import time
import numpy as np
from pylab import *
from matplotlib import pyplot as plt

file_path = '/media/ABB4-4F3A/DATALOG.TXT'

def split_in_blocks(txt_file, pattern):
	'''
	Find the last appears of the text that indicate a new flight and divide in the number of blocks generated by the rocket
	Return: A list that contains all the different blocks of data and a list containing the header.
	'''
	num_times_find_pattern = []
	for num_line, line in enumerate(fileinput.input(txt_file)):
		if pattern in line:
			num_times_find_pattern.append(num_line)
		if num_line == 0:
			header = list(line.strip().split(","))
			#print header
	blocks_of_data = []
	with open(txt_file) as f:
		lines = f.readlines()
		for num_header_line in num_times_find_pattern: 
			if num_header_line == 0:
				num_header_line_prev = num_header_line
			else:
				block_lines = lines[num_header_line_prev + 1 : num_header_line - 1]
				blocks_of_data.append(block_lines)
				num_header_line_prev = num_header_line
		block_lines = lines[num_header_line_prev + 1 : num_line + 1]
		blocks_of_data.append(block_lines)
	return blocks_of_data, header

def manage_data_from_blocks(blocks, header):
	'''
	Divide al the text in blocks tagged with their type of data (accelaration, temperature, ...) continued by a number of block
	Return: A dict that contains all the different types of data diferentiated and numbered.
	'''
	blocks_dict = collections.OrderedDict()
	for block_number, block in enumerate(blocks):
		for item in header:
			blocks_dict['%s%s' % (item,block_number)] = []
		for line in block:
			line_list = line.strip().split(",")
			blocks_dict['f%s' % block_number].append(int(line_list[0]))
			blocks_dict['ax%s' % block_number].append(float(line_list[1]))
			blocks_dict['ay%s' % block_number].append(float(line_list[2]))
			blocks_dict['az%s' % block_number].append(float(line_list[3]))
			blocks_dict['gx%s' % block_number].append(float(line_list[4]))
			blocks_dict['gy%s' % block_number].append(float(line_list[5]))
			blocks_dict['gz%s' % block_number].append(float(line_list[6]))
			blocks_dict['mx%s' % block_number].append(float(line_list[7]))
			blocks_dict['my%s' % block_number].append(float(line_list[8]))
			blocks_dict['mz%s' % block_number].append(float(line_list[9]))
			blocks_dict['t%s' % block_number].append(float(line_list[10]))
			blocks_dict['p%s' % block_number].append(int(line_list[11]))
			blocks_dict['h%s' % block_number].append(float(line_list[12]))
	#print blocks_dict.keys()
	return blocks_dict

def process_data(blocks_dict):
	fingerprints = []
	temperatures = []
	pressures = []
	heights = []
	accel_x = []
	accel_y = []
	accel_z = []
	magn_x = []
	magn_y = []
	magn_z = []
	gyro_x = []
	gyro_y = []
	gyro_z = []
	for block in blocks_dict:
		if block.startswith('f'):
			fingerprints.append(block)
		if block.startswith('t'):
			temperatures.append(block)
		if block.startswith('p')
			pressures.append(block)
		if block.startswith('h')
			heights.append(block)
		if block.startswith('ax'):
			accel_x.append(block)
		if block.startswith('ay'):
			accel_y.append(block)
		if block.startswith('az')
			accel_z.append(block)
		if block.startswith('mx'):
			magn_x.append(block)
		if block.startswith('my'):
			magn_y.append(block)
		if block.startswith('mz')
			magn_z.append(block)
		if block.startswith('gx'):
			gyro_x.append(block)
		if block.startswith('gy'):
			gyro_y.append(block)
		if block.startswith('gz')
			gyro_z.append(block)
	#print blocks_dict.keys()	
	fingerprint_basic_info = basic_process_fingerprints(fingerprints)
	temp_basic_info = basic_process_temperatures(temperatures)
	print_temp_evolution(fingerprints, temperatures)
	#print fingerprint_basic_info
	#print temperatures_basic_info

def basic_process_fingerprints(fingerprints):
	fingerprint_basic_info = collections.OrderedDict()
	for fingerprint_block in fingerprints:
		millis_interval_list = []	
		for position, millis in enumerate(blocks_dict[fingerprint_block]):
		 	if position != 0:
		 		millis_interval = millis - millis_prev
		 		millis_interval_list.append(millis_interval)
		 	millis_prev = millis
		fingerprint_basic_info[fingerprint_block] = {}
		millis_average = sum(millis_interval_list) / len(blocks_dict[fingerprint_block])
		fingerprint_basic_info[fingerprint_block]["Av"] = millis_average
		millis_max = max(millis_interval_list)
		fingerprint_basic_info[fingerprint_block]["MAX"] = millis_max
		millis_min = min(millis_interval_list)
		fingerprint_basic_info[fingerprint_block]["MIN"] = millis_min
	return fingerprint_basic_info

def basic_process_temperatures(temperatures):
	temp_basic_info = collections.OrderedDict()
	for temp_block in temperatures:
		temp_basic_info[temp_block] = {}
		temp_average = sum(blocks_dict[temp_block]) / len(blocks_dict[temp_block])
		temp_basic_info[temp_block]["Av"] = "%.2f" % temp_average 
		temp_max = max(blocks_dict[temp_block])
		temp_basic_info[temp_block]["MAX"] = temp_max
		temp_min = min(blocks_dict[temp_block])
		temp_basic_info[temp_block]["MIN"] = temp_min
	return temp_basic_info

def print_temp_evolution(fingerprints, temperatures):
	plt.figure(1)
	for num in range(len(fingerprints)):
		x = blocks_dict[fingerprints[num]]
		y = blocks_dict[temperatures[num]]
		#subplot(nrows, ncols, plot_number)
		nrows = int(math.ceil(float(len(fingerprints) / 3.0)))
		ncols = 3
		subplot_index = "%s%s%s" % (nrows, ncols, num + 1)
		plt.subplot(subplot_index)

		plt.plot(x, y, linewidth=1.0, color="green")
		xlabel('time (milliseconds)', fontsize = 8)
		ylabel('temperature (C)', fontsize = 8)
		#title('', fontsize=10)
		grid(True)
		plt.xticks(blocks_dict[fingerprints[num]][::len(blocks_dict[fingerprints[num]])/10], rotation=30, fontsize=8)
		plt.annotate('Despegue', xy=(2200, 34.82), xytext=(2300, 34.88),
				bbox=dict(boxstyle="round", fc="0.8"),
	            arrowprops=dict(facecolor='black', shrink=0.05),
	            )
		plt.annotate('Paracaidas', xy=(7200, 34.82), xytext=(6300, 34.88),
	            arrowprops=dict(facecolor='black', shrink=0.05),
	            )
		axvline(x=2200)
		axhspan(34.80, 34.82, facecolor='0.5', alpha=0.5, color="red")
		plt.ylim(min(blocks_dict[temperatures[num]]) - 0.02, max(blocks_dict[temperatures[num]]) + 0.02)
		plt.yticks(fontsize=8)
	plt.suptitle('temperatures in data', fontsize=12)
	plt.show()
	
#start = time.time()
blocks, header = split_in_blocks(file_path, "m")
blocks_dict = manage_data_from_blocks(blocks, header)
process_data(blocks_dict)

#stop = time.time()
#total_time = stop -start
#print total_time